version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: apache-beam[gcp]
    versions:
    - 2.28.0
  - dependency-name: numpy
    versions:
    - 1.20.0
