version: '3'

services:
  grobid-trainer:
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud

  tools:
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud

  tools-dev:
    volumes:
      - ./sciencebeam_trainer_grobid_tools:/opt/grobid-training/sciencebeam_trainer_grobid_tools
      - ./tests:/opt/grobid-training/tests
    environment:
        # avoid issues with .pyc/pyo files when mounting source directory
        PYTHONOPTIMIZE: ""
        PYTHONDONTWRITEBYTECODE: "1"

  tools-docker:
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
